appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: qdwODmHdI6BWI2EHOE/k5XVjRi2BT2wJUt8W100e85Z7R/X5Ayjp9cVa/1jZB+i8cUx4spqI6iz0zjdyEFSSEizoLEmDvC8boatYA37AMR3MIfWKjTZ4G75rq3A8xEd4fp3IWl+8mLLbdzMZ9DkXiDZBd4xCa9mV5KEDhonb/rLr/Oh1MXD2bGoaU3zBQdzOmMcpE5GgftikPJGstLYFare90IaIB3Tj4PyjjrEtvgPgolIbA6FuBEsMblfMK+XWCgIcENX/cDyvBzMffCeM8b7AyTOSQPVKGfTCOf9xSgKcijJ7BH9t127oitqMEkt/fyXv6GkLlKjlL6i397Lv7mOHpWs96mjyQQXtPFfyy7EzNHWH5RPhFQRAIcG49q3Pjzv6ZTGv9OntU98wbkmB0e8XmFAxfF4XmNcqJie0D/fWR2og68Xjt+zToQce2Q4Gvbg/W9AW5gFcqhn1231zwM0vQ4wL8XssC+WR2M22uMErIxlqmelyNxcrkwHT828gfYQxLmkuyNTkJvF/QyPzCAt3uU99PIvOaOwi3cS5y1VFIoiD6/nwwSkniJYQz+kTo+n7dfRfn/tCN85m8yqYoEO7Y8y4hjhU3RhNdDTZtjpDtmRUb4ycLxnmtYH5Dc6geZU/x7hxAcv+gKIcfMqchzoJEsix59sJk2TOUwF/muU=}
provider:
  win: azure
conda_forge_output_validation: true
